//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class YoloObject
    {
        public int Id { get; set; }
        public string ClassName { get; set; }
        public byte[] Image { get; set; }
        public string Hash { get; set; }
        public double X1 { get; set; }
        public double Y1 { get; set; }
        public double X2 { get; set; }
        public double Y2 { get; set; }
        public double Confidence { get; set; }
        public int FotoId { get; set; }
    
        public virtual Foto Foto { get; set; }
    }
}
